[database]
url = "postgres://admin:REDACTED_DB_PASSWORD@@101.33.75.40:22303/postgres"

[redis]
url = "redis://:REDACTED_REDIS_PASSWORD@101.33.75.40:10279/"

[server]
address="0.0.0.0:8443"
locales="zh-CN"

[quic_server]
address="0.0.0.0:4433"

