[database]
url = "postgres://postgres:REDACTED_DB_PASSWORD_LOCAL@127.0.0.1:5432/postgres"

[redis]
url = "redis://:REDACTED_REDIS_PASSWORD@101.33.75.40:10279/"

[server]
address="0.0.0.0:8443"
locales="zh-CN"

[quic_server]
address="0.0.0.0:4433"

