[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
rbatis = { workspace = true }
rbdc-pg = { workspace = true }
rbdc-pool-fast = { workspace = true }
validator = { workspace = true }
anyhow = { workspace = true }
rbs = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
dotenvy = "0.15"
tracing-subscriber = { workspace = true }
